### ISSUE TITLE
does httpd work on your u-boot?

### ISSUE THREAD

**Issue by i3roly** [SWRT-dev/bluecave-asuswrt#28]
does your httpd command work?

i am trying to port the version from prpl to newer u-boot.

but when i try to access the server it just says:
```
=> setenv ipaddr 192.168.2.1
=> httpd
Waiting for PHY link
Using PHY at addr 2, speed 1000, duplex 1
http server start...
opt=02
opt=02
```
but i don't see any webpage or anything. is this becasue i'm testing u-boot through "go 80400000" after tftp upload?

**Comment by paldier** [comment]
You need to initialize the network, NOTE, uboot is single threaded bootloader.

**Comment by i3roly** [comment]
How do I initialise the network? I thought setenv serverip, setenv ipaddr, was enough.

bless,
g
From: paldier
Sent: Monday, 26 December 2022 11:20 PM
To: SWRT-dev/bluecave-asuswrt
Reply To: SWRT-dev/bluecave-asuswrt
Cc: gagan sidhu; Author
Subject: Re: [SWRT-dev/bluecave-asuswrt] does httpd work on your u-boot? (Issue #28)


You need to initialize the network, NOTE, uboot is single threaded bootloader.

**Comment by i3roly** [comment]
fixed it.

it was my fault because the older httpd code uses NetCksum which is not the same as compute_ip_checksum.

wow this httpd server is very primitive compared to RALink's, but i know it's the same. at least it is a good starting point.

now to get my ax50 out of brick mode. very strange device. could not use u-boot.ltq.uart like expected. have to do "two stage" by sending uart.txt file first, and then u-boot.ltq.uart. 

and flashing u-boot.bin to nand doesn't work. very very strange device lol
